### ISSUE TITLE
Feedback on reducing duplication in CSS media queries

### ISSUE THREAD

**Issue by nselikoff** [thetechtakeover/Movies#5]
I don't expect you to go back and edit all of your CSS, but did want to point out a few things I'm noticing to help you level up:

Let's take a look at one of your CSS classes, `.movie_wrapper`:

Default style is declared here:
https://github.com/thetechtakeover/Movies/blob/master/style.css#L180

```css
.movie_wrapper {
    margin-top: 0;
    display: flex;
    justify-content: space-evenly;    
}
```

Mobile style is declared here:
https://github.com/thetechtakeover/Movies/blob/master/style.css#L347

```css
.movie_wrapper {
    margin-top: 100px;
    display: flex;
    flex-direction: column; 
    margin:0;   
}
```

Tablet style is declared here:
https://github.com/thetechtakeover/Movies/blob/master/style.css#L475

```css
.movie_wrapper {
    margin-top: 100px;
    display: flex;
    flex-direction: column;
    margin:0;   
}
```

Desktop style is declared here:
https://github.com/thetechtakeover/Movies/blob/master/style.css#L549

```css
.movie_wrapper {
    margin-top: 100px;
    display: flex;
    justify-content: space-evenly;    
}
```

1. There's a lot of duplication here, which will make it hard to maintain your CSS, and easy for bugs to crop up. Any properties that you want to apply regardless of screen size (e.g. `display: flex;`) can just be defined once in the first section... you don't need to repeat them in the subsequent sections.

2. A couple of times you've used both `margin-top` and `margin` in the same CSS class. The order these are in means that the `margin-top` rule will have no effect, because the `margin: 0;` rule sets all margins to zero, and because it comes after `margin-top: 100px`, it has more priority.

3. Take a "mobile first" approach - think about all your base styles as applying to mobile screen sizes (and in fact, when you're working on your site, use the developer tools in your browser to preview it at a mobile screen size.) Then you don't need media queries for mobile screen sizes at all, just for tablet and desktop. Within the tablet and desktop media query sections, just selectively apply overrides as needed.
